### ISSUE TITLE
can't find the dir "optimizationtools"

### ISSUE THREAD

**Issue by szu-lisili** [fontanf/setcoveringsolver#1]
hi, this is a nice work, but I can't find the directory "optimizationtools", is there any way to get it?

**Comment by fontanf** [comment]
Yes, it's here https://github.com/fontanf/optimizationtools
Note that if you use Bazel to compile, it is automatically downloaded

**Comment by szu-lisili** [comment]
> Yes, it's here https://github.com/fontanf/optimizationtools
> Note that if you use Bazel to compile, it is automatically downloaded

thanks!
