### ISSUE TITLE
Is it possible to provide related information about reduce rule?

### ISSUE THREAD

**Issue by WCommm** [fontanf/setcoveringsolver#4]
Hi, I am a beginner of set covering problem. The repo is very excellent, and I learned a lot from it. But there are some confused concepts like mandatory set, identical element, etc. in reduce rules.  Is it possible to provide related information about reduce rule? Thanks.

**Comment by fontanf** [comment]
Hi,

These are classical reductions for the set covering problem.

For example
* If an element is covered by a single set, then it is mandatory to use this set
* If tow sets or two elements are identical, then one of them can be removed from the problem

**Comment by WCommm** [comment]
Thanks for your reply.
